-- an attributr that specifies the type of data in a column of our database -table
--
 -- most widely used are
--numeric-int double float DECIMAL
--string-varchar
--date - date
--boolean- boolean
 --
--deciaml(5,2)  total digit 5 out of which 2 are decimal
 --
--PRIMARY KEY
--the primary key constraints uniquely identifies each record in a table
--primary keys must contain unique values and cannot contain null values
--a table can have only one primary key