-- STORED ROUTINE
-- An sql statement
-- or a
-- set of sql statement that can be stored on database server which can be call no. of time
 -- Types of stored routine
--  1. stored procedure
-- 2. user defined functions